export const TransactionType = {
  TYPE_PAYMENT: 0,
  TYPE_CHILD_ACCOUNT: 10,

  SUBTYPE_PAYMENT_ORDINARY_PAYMENT: 0,
  SUBTYPE_PAYMENT_PRIVATE_PAYMENT: 1,

  SUBTYPE_CHILD_CREATE: 0,
  SUBTYPE_CHILD_CONVERT_TO: 1,
}